
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


#rofi
windowrule = match:class ^(rofi)$, opacity 0.9 0.9

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.01, match:namespace rofi

#zen-b
windowrule {
    name = hide-zen-border
    match:class = ^(zen.*)$
    border_size = 0
}
#transparent vesktop
windowrule {
    name = transparent-desktop
    match:class = ^(vesktop)$
    opacity = 0.8 0.8
}

layerrule {
    name = musicwidget_blur
    match:namespace = ^musicwidget$
    blur = on
    ignore_alpha = 0.1
}


#sc
windowrule {
    name = scratchpad-vesktop
    match:class = ^(vesktop)$
    workspace = special:discord
}

windowrule {
    name = scratchpad-spotify
    match:class = ^(Spotify)$
    workspace = special:spotify
}
